### ISSUE TITLE
Implementing recommended improvements

### ISSUE THREAD

**Issue by bigfattbagg** [twomice/com.joineryhq.reltoken#11]
I love this extension and what it can do. However, I have too many contacts that have more than one relationship of a given type. The related tokens I need is not always the relationship with the highest internal ID.
This has been explained under “Room for Improvements” in the Read Me section. 
Is there anyone that can help to implement this improvement?

**Comment by twomice** [comment]
Hi @bigfattbagg . Yes, we're glad to help with this, though considering the complexity I should mention that it would probably turn into a paid project. But for now, we can at least flesh out the need.

My first two questions are:
1. Can you give a little more detail and some examples about your situation? 
2. Can you think of any consistent rule that describes how you would want to handle tokens for multiple relationships? I.e., to take an example from the README, if you're sending a mailing to 20 parents, each of whom have "parent/child" relationships with multiple children, how would you like the extension to handle the _Related (Child)::First Name_ token? (Or of course please feel free to use an example that more closely fits your situation.)

Thanks,
Allen

**Comment by bigfattbagg** [comment]
Hi @twomice thank you for your response.

To answer your two questions:

1. Most of the time I will use Print/Merge Document function. I will create letter to parent with multiple “parent/child” relationship. However, the letter I want to generate isn’t always the one with the relationship of the highest internal ID

2. I will like to have the option to select which relationship I want for generating the letter.
Eg.
I might want to create letters for 20 parents (using the same message template) and each parent might have “parent/child” relationship with multiple children. So I want to select for each parent which relationship token should be populated for my letters.

**Comment by twomice** [comment]
Thanks for the details, @bigfattbagg . In your parent/child example, it sounds like you need to be able to make a completely arbitrary choice based on your own knowledge of the parents and children at the time when you send out the mailing.  To do this, you would need an interface to manually review all 20 parents and all of their parent/child relationships, so that you could manually select the correct child for each parent.  Unfortunately, I think that kind of thing is outside the scope of this extension.

It's conceivable that another custom extension could be built to solve this kind of problem, because in the end token values are defined by a hookable procedure. But you might have to do some careful analysis to decide whether the cost of developing that extension is justified, compared to the business value it would provide.
