### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by bmango** [twomice/com.joineryhq.reltoken#17]
Using php 7.4 I'm getting the error message above. This seems to be coming from line 169 in reltoken.civix.php. I have swapped

```if ($entry{0} == '.') {```

with

```if ($entry[0] == '.') {```

Which I think has fixed it

**Comment by lucky091588** [comment]
Hi @bmango. I think you have an older version of this extension, since I can't find the `if ($entry{0} == '.') {` on the latest reltoken.civix.php. I have found that line on the old version of the file though, which you can see in [here](https://github.com/twomice/com.joineryhq.reltoken/commit/554f0c2bde8ad221a9355fa80edfcfa5d6ac6939#diff-00ae82e0824e2b77aa13726e5b21a20c7bd3c9e3ad767b0cb1db3a11137b2f06L169), and it was already updated last Feb 2021.

**Comment by bmango** [comment]
Ok, thanks!
