### ISSUE TITLE
The tokens not working here 

### ISSUE THREAD

**Issue by jnajajreh** [twomice/com.joineryhq.reltoken#21]
Dears
I am using civicrm from one year and I am using Related token extension, we used to use it to send thank you letter for the head of organization, so I am using the relationship type ("Head of") in my template, but unfortunately I have issue in displaying the address of the head and other information, the email token is working well,  would you please help us to solve this issue? I appreciate your help 
Civicrm 5.46.2

![1](https://user-images.githubusercontent.com/49274375/155471577-d1c0bd86-3f2e-45e6-9916-a104eae5d428.png)
![1-1](https://user-images.githubusercontent.com/49274375/155471583-62ad5594-427b-4067-bf23-502f960aa1db.png)
![2](https://user-images.githubusercontent.com/49274375/155471586-111495de-ec60-4e22-a2a5-3fcaed1a847f.png)

**Comment by twomice** [comment]
Thank you for the report. 

Here's what I'm seeing:

* This extension will exhibit such problems (some related tokens simply won't display their values) in some newer versions of civicrm (not sure what's the latest compatible version, but perhaps as early as 5.43.x), because it relies on a deprecated utiltity function in CiviCRM core (`CRM_Utils_Token::getTokenDetails()`)
* To be compatible with newer versions of CiviCRM core, the extension should be modified to use the Token Processor approach described at https://docs.civicrm.org/dev/en/latest/framework/token/

**Comment by MegaphoneJon** [comment]
@jnajajreh - I think my new version of this extension (https://github.com/MegaphoneJon/com.joineryhq.reltoken/archive/refs/heads/token-processor.zip) fixes your problem.  Could you please try it and let us know?

**Comment by jnajajreh** [comment]
Many thanks I will do

**Comment by twomice** [comment]
Thanks for responding @MegaphoneJon .  Curious, does your linked version ([this comment](https://github.com/twomice/com.joineryhq.reltoken/issues/21#issuecomment-1168067503)) contain anything other than PR #22 (now merged into this repo as of v0.4.0)? I'd be glad to get a PR on any additional improvements you might have made.

**Comment by twomice** [comment]
@jnajajreh and @MegaphoneJon:  As of version 0.4.0, I think this repo now contains all the fixes from Jon's github fork repo (unless Jon can point out others). @jnajajreh I'm inclined to close this on the assumption that this version will address your issue. Please comment here if that's not so. Thanks!

**Comment by MegaphoneJon** [comment]
This looks good to close.

**Comment by twomice** [comment]
Thanks @MegaphoneJon .
